### ISSUE TITLE
Was bored, so did a "code review"

### ISSUE THREAD

**Issue by miyoyo** [g-apparence/flutter_mvvm#1]
Put it at https://github.com/miyoyo/flutter_mvvm.
Feel free to take whatever you want from it, or ignore it 🤷‍♀️

Also, just a passing thought, but are you _sure_ this is MVVM and not some kind of MVP-MVVM hybrid? Not exactly sure what a presenter is doing here, but then again I'm no expert on the pattern.

**Comment by g-apparence** [comment]
Thank you for this 👍. Could you send this as a pull request on this repository ?
So I can actually see all your suggestions and diff.

Yes, you are right it's inspired from mvp / mvvm from android trends. Android used mvp then mvvm to hold pages states. That's the version I prefered and then tryed to port on flutter.
