### ISSUE TITLE
Why not use ChangeNotifierProvider?

### ISSUE THREAD

**Issue by jasonlee3652** [g-apparence/flutter_mvvm#6]
replace PresenterInherited to ChangeNotifierProvider
let MVVMModel extends ChangeNotifier, so not need forceRefreshView method, use  MVVMModel.notifyListeners().
What do you think?

I like your way of thinking, it can divide the logic very well, but I don’t understand whether this is mvvm or mvc.

**Comment by g-apparence** [comment]
Hi, 
We made this at a time changenotifier didn't exist, so this could be a nice rework idea. 
But today, we use to wrap some `ValueNotifier` in our model to manage small page refreshing. 
[exemple here ](https://github.com/Apparence-io/pal-plugin/blob/master/lib/src/ui/editor/pages/helper_editor/helpers/editor_fullscreen_helper/editor_fullscreen_helper_viewmodel.dart)
```dart
class FullscreenHelperViewModel extends HelperViewModel {
  ....
  LanguageNotifier language;
  BoxNotifier bodyBox;
  MediaNotifier media;
  TextFormFieldNotifier titleField;
  TextFormFieldNotifier descriptionField;
  TextFormFieldNotifier positivButtonField;
  TextFormFieldNotifier negativButtonField;
...
```


**For the mvvm or mvc point**
It's more a mix of mvvm / mvp approach, trying to take the best of both worlds. Mvp doesn't share a model but methods. This is not really fun as you have to create a method for too many things. 
To not confuse people we plans to migrate the lib name to something else.

**Comment by jasonlee3652** [comment]
PresenterInherited

`  @override
  bool updateShouldNotify(PresenterInherited oldWidget) => true;`

use ValueNotifier will Lead to MvvmContentBuilder rebuild, Same effect as use forceRefreshView

**Comment by jasonlee3652** [comment]
Thanks, I understand why I did this
